services:
 web:
   build: .
   command: gunicorn --bind 0.0.0.0:8000 InventoryManagementSystem.wsgi:application
   container_name: app-docker
   ports:
     - "8000:8000"
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
   env_file:
     - .env