# Generated by Django 5.1.6 on 2025-02-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_asset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
    ]
